### ISSUE TITLE
For SIRIUS, focus on the option to run 

### ISSUE THREAD

**Issue by gflofst** [michaelsevilla/paulocto-popper#17]
Ok. Margaret, Jeff, and I talked about this a bit and I think I have the way to keep this clear and make both papers positive about everything:
 
The HotStorage paper talks about how to use the objector function within Ceph's CLS functionality to replicate things like directory trees to support ROOTS. EMPRESS is there to store the objector function and additional data characteristic metadata. It is not required to run the objector function and can even be skipped in cases where no additional data features are used for query/selection. Instead the objector function alone can generate the object names to return the right objects.
 
The issue is the explosion of objects returned potentially and the need to extend the objector function to limit the onslaught of returned objects. This is a few more parameters and a series of calls. There is also the issue of how to handle a series of runs and multiple applications. The object count and name space grows out of control. Even with the objector function eliminating having to store all of the keys to find the data again, the key space is unmanageably large.
 
The SC paper shows the more general case where EMPRESS still stores the objector function and the data characteristics. However, the test case is for decomposing a globally distributed array (chunked into Ceph objects) instead of a directory tree. Also, instead of having to use Ceph as the data storage layer, any object store or even any storage mechanism (including an HDF5 or ADIOS file) could be used to hold the data. The actual return from the objector function will vary depending on the storage medium (and it would require to be provided for each one). For an HDF5 file set, for example, a set of file names, group path + var names, and hyperslabs would be returned instead of object names. For Ceph, all of that is incorporated into the object name in some form (along with some different information).
 
I hope that works for everyone. I prefer papers that keep things positive and say, "we wish we could do this, but couldn't" rather than, "this solution was terrible, so we made a better one". In this case it is, "since we have this specialization optimization option, look at what we can do" rather than "EMPRESS is making a mess of things so we handled it in Ceph".

Here is a new Takeaway suggested text:
The SIRIUS system stores as much as 1 triliion or more objects for a single large scale simulation run. By decoupling the namespace we enable getting the scalability advantages of object stores for simulation and engineering workloads. However, SIRIUS is focused on managing the object set for that single, large scale run and not the greater namespace issues related to multiple runs and multiple applications. A typical POSIX hierarchical namespace addresses this through nested or peer directories. Another management level is needed to address the greater collection of runs level. The bottleneck becomes traversing the object collections for a series of runs and for each application. Additional namespace management is required.

For the "Does this solve the problem?", how about saying that by adding another layer to the generated name space, we can cut down the search space dramatically keeping the object system managable?

**Comment by michaelsevilla** [comment]
... now to start tailoring the rest of the section to this "takeway"...

**Comment by michaelsevilla** [comment]
Thanks, Jay, Margaret!

I took all your suggestions except for comments about the size of the *total* object metadata space... I see how the objecter can cut down on the search space but wasn't sure how that helps manage the large number of objects internally -- how it helps keep the namespace in check.

**Comment by michaelsevilla** [comment]
I'm going to start cutting the paper down in to 5 pages... so more of your content might get taken out. The only thing I really want to keep in there is the size of object name list and how passing the objecter around is better than passing around the whole name list.

**Comment by gflofst** [comment]
Yes, I wish I had realized it was a 5 pager. Most of this will have to be cut.

Thanks for your efforts and including is.

Best,

Jay

On Mar 15, 2018, at 12:50 AM, Michael Sevilla <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm going to start cutting the paper down in to 5 pages... so more of your content might get taken out. The only thing I really want to keep in there is the size of object name list and how passing the objecter around is better than passing around the whole name list.

**Comment by michaelsevilla** [comment]
5 pages is good thing for you guys... more content for your other future papers. :)
