### ISSUE TITLE
biblio: cite ROOT tutorials

### ISSUE THREAD

**Issue by michaelsevilla** [michaelsevilla/paulocto-popper#23]

**Comment by reza-nasirigerdeh** [comment]
1. Add the abstract to the paper :)

Section 2.2 High Energy Physics
2. "The  High  Energy  Physics  (HEP)  community  uses  a framework called ROOT " ->  
The  High  Energy  Physics  (HEP)  community  uses  a framework called ROOT [] 
 Add this citation to ROOT framework 
@article{root:paper,
      author         = "Brun, R. and Rademakers, F.",
      title          = "{ROOT: An object oriented data analysis framework}",
      booktitle      = "{New computing techniques in physics research V.
                        Proceedings, 5th International Workshop, AIHENP '96,
                        Lausanne, Switzerland, September 2-6, 1996}",
      journal        = "Nucl. Instrum. Meth.",
      volume         = "A389",
      year           = "1997",
      pages          = "81-86",
      doi            = "10.1016/S0168-9002(97)00048-X",
      SLACcitation   = "%%CITATION = NUIMA,A389,81;%%"
}

3." For this discussion, the following objects are of interest: a “Tree” is a table of a collection of events, listed sequentially and stored in a flat namespace; a “Branch” is a data container representing columns of a Tree; and “Baskets” are byte ranges partitioned by events and indexed  by  LRHs.   Clients  request  Branches  and  data  is transferred as Baskets; so Branches are the logical view of the data for users and Baskets are the compression, parallelization, and transfer unit." 

I change the above paragraph a little bit to cite the first technical report: 
For this discussion, the following objects are of interest: a “Tree” is a table consisting of events (i.e. each row of the table indicates an event), listed sequentially and stored in a flat namespace; a “Branch”  represents a column of the Tree and contains an ordered set of column values known as "Branch Entries" grouped into an ordered set of data units called  “Baskets” [] . Clients  request  a range of branch entries  and  data  is transferred as Baskets containing those branch entries; so Branch Entries are the logical view of the data for users and Baskets are the compression, parallelization, and transfer unit.

@techreport{root:cs,
  title={ROOT Files for Computer Scientists},
  author={NasiriGerdeh, Reza and Pivarski, Jim and Sevilla, Michael A. and Maltzahn, Carlos},
  number = {UCSC-SOE-18-09},
  institution = {UC Santa Cruz},
  month = {May},
  year = "2018"
}

4. Paragraph just before the end paragraph of Section 2.2 High Energy Physics:
Namespace Size: ....   To quantify (2), the read and write runtime over six runs of replaying a trace of Branch access from the NTupleMaker application is shown in Figure 3c, ...

I change it a little bit to cite the second technical report:
 To quantify (2), we employed a  trace of accesses from the NTupleMaker application. We used RootUtils [] library to translate the accesses which were in the form of (file offset, size)  to the corresponding branches in the ROOT file. The read and write runtime over six runs of replaying the trace of branch access  is shown in Figure 3c, ...

@techreport{rootutils,
  title={RootUtils: a Library to Better Understand ROOT Files},
  author={NasiriGerdeh, Reza and Pivarski, Jim and Tadel, Matevz and Sevilla, Michael A. and Maltzahn, Carlos and Bockelman, Brian and  Wurthwein, Frank},
  number = {UCSC-SOE-18-10},
  institution = {UC Santa Cruz},
  month = {May},
  year = "2018"
}
