### ISSUE TITLE
paper: jay and margaret's comments and citations

### ISSUE THREAD

**Issue by michaelsevilla** [michaelsevilla/paulocto-popper#7]
- [x] integrate scale-out read/gather discussion into problem 
- [x] cite LWFS and SSIO project (Carns and ROSS)
- [x] update # of object with more accurate timestamps and fix 10K bug identified by Margaret
- [x] tout the flexibility of EMPRESS; namely that granularity is treated as a first class citizen
- [x] differentiate between state of the art and EMPRESS for storing object names
- [x] differentiate between state of the art and EMPRESS for finding features of interest

**Comment by michaelsevilla** [comment]
Also make sure to address Margaret's comments.

**Comment by michaelsevilla** [comment]
Question for Margaret/Jay:
- [x] For this paper, the objecter function is the solution but in Section 2.3 I'm just trying to show the problem. Today, does the objecter function exist inside Empress or does Empress store object name lists? I'm trying to show the problem that we need calculated naming but the reasoning is EITHER:
    - Empress storage footprint will get too big or
    - we don't want to shove a huge object list back to the client. 

- [x] Is Figure 7 a correct drawing of how Empress works today?
- [ ] Please make sure my "Takeaway" paragraph is correct. I don't want to misrepresent Empress

**Comment by gflofst** [comment]
I'll let Margaret answer. She is on task today, for the most part. I'll add in other comments in an hour or so.

Best,

Jay

On Mar 14, 2018, at 10:34 AM, Michael Sevilla <notifications@github.com<mailto:notifications@github.com>> wrote:


Question for Margaret/Jay:

  *    For this paper, the objecter function is the solution but in Section 2.3 I'm just trying to show the problem. Today, does the objecter function exist inside Empress or does Empress store object name lists? I'm trying to show the problem that we need calculated naming but the reasoning is EITHER:

     *   Empress storage footprint will get too big or
     *   we don't want to shove a huge object list back to the client.
  *    Is Figure 7 a correct drawing of how Empress works today?

  *    Please make sure my "Takeaway" paragraph is correct. I don't want to misrepresent Empress
